# https://developers.home-assistant.io/docs/add-ons/configuration#add-on-dockerfile
build_from:
  aarch64: "ghcr.io/home-assistant/aarch64-base:3.15"
labels:
  org.opencontainers.image.title: "Home Assistant Add-on: Jacket add-on"
  org.opencontainers.image.description: "Jackett server addon"
  org.opencontainers.image.source: "https://github.com/cazac9/Jackett"
  org.opencontainers.image.licenses: "Apache License 2.0"
args:
  TEMPIO_VERSION: "2021.09.0"
